{
 "title": "Switch dashboard",
 "tags": [
  "Cisco",
  "Datacenter",
  "Nexus",
  "hardware"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "display",
    "label": "Historique",
    "query": "30s-for-1w,5m-for-52w,1h-for-10y"
   },
   {
    "name": "producer",
    "label": "Host",
    "query": "SHOW TAG VALUES WITH KEY = \"source\""
   }
  ]
 },
 "panels": [
  {
   "title": "Hostname",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "show version",
     "select": [
      [
       { "params": [ "host_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$producer$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "show version",
     "query": "SELECT last(\"kern_uptm_days\" ) * 1440 + last(\"kern_uptm_hrs\" ) * 60 + last(\"kern_uptm_mins\" )  FROM \"show version\" WHERE (\"source\" =~ /^$producer$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "kern_uptm_days" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "Leaf-101" }
     ]
    }
   ]
  },
  {
   "title": "Chassis ID",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "show version",
     "select": [
      [
       { "params": [ "chassis_id" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$producer$/" }
     ]
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "show version",
     "query": "SELECT last(kickstart_ver_str) FROM \"show version\" WHERE (\"source\" =~ /^$producer$/)",
     "select": [
      [
       { "params": [ "kickstart_ver_str" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$producer$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "show system resources",
     "select": [
      [
       { "params": [ "cpu_state_user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "mean_cpu_state_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "mean_mean_cpu_state_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$producer$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "show environment temperature",
     "select": [
      [
       { "params": [ "curtemp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Température" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$producer$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Usage Mémoire",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sys/procsys/syscpusummary",
     "query": "SELECT last(\"memory_usage_used\") / last(\"memory_usage_total\") * 100   FROM \"show system resources\" WHERE (\"source\" =~ /^$producer$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "producer", "operator": "=~", "value": "/^$producer$/" }
     ]
    }
   ]
  },
  {
   "title": "Power supply 1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "actual input",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "show environment power",
     "select": [
      [
       { "params": [ "actual_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$producer$/" },
      { "condition": "AND", "key": "powersup/TABLE_psinfo", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "actual output",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "show environment power",
     "select": [
      [
       { "params": [ "actual_out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$producer$/" },
      { "condition": "AND", "key": "powersup/TABLE_psinfo", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Power supply 2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "actual input",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "show environment power",
     "select": [
      [
       { "params": [ "actual_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$producer$/" },
      { "condition": "AND", "key": "powersup/TABLE_psinfo", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "actual output",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "show environment power",
     "select": [
      [
       { "params": [ "actual_out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$producer$/" },
      { "condition": "AND", "key": "powersup/TABLE_psinfo", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Dynamic mac-addresses count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "local MAC addresses",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "show mac address-table count",
     "select": [
      [
       { "params": [ "TABLE_macaddtblcount/dyn_cnt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$producer$/" }
     ]
    },
    {
     "alias": "remote MAC addresses",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "show mac address-table count",
     "select": [
      [
       { "params": [ "TABLE_macaddtblcount/otv_cnt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$producer$/" }
     ]
    }
   ]
  },
  {
   "title": "MAC addresses",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "TABLE_mac_address" ], "type": "tag" }
     ],
     "measurement": "show mac address-table dynamic",
     "query": "SELECT \"disp_vlan\" FROM \"show mac address-table dynamic\" WHERE (\"source\" =~ /^$producer$/)  GROUP BY \"TABLE_mac_address\"",
     "select": [
      [
       { "params": [ "disp_vlan" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "disp_port" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$producer$/" }
     ]
    }
   ]
  },
  {
   "title": "VNI up",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "VNIs",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "show nve vni summary",
     "query": "SELECT mean(\"cp_vni_up\") FROM \"show nve vni summary\" WHERE (\"source\" =~ /^$producer$/) AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "cp_vni_up" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$producer$/" }
     ]
    }
   ]
  },
  {
   "title": "VNI down",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "VNIs",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "show nve vni summary",
     "select": [
      [
       { "params": [ "cp_vni_down" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$producer$/" }
     ]
    }
   ]
  },
  {
   "title": "BGP peers established",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sys/bgp/inst",
     "query": "SELECT last(\"numEstPeers\") FROM \"sys/bgp/inst\" WHERE (\"source\" =~ /^$producer$/) AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "numEstPeers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "producer", "operator": "=~", "value": "/^$producer$/" }
     ]
    }
   ]
  },
  {
   "title": "BGP peers established",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Peer Established",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sys/bgp/inst",
     "query": "SELECT sum(peer) FROM (SELECT last(\"numPeers\") as peer FROM \"sys/bgp/inst\" WHERE (\"source\" =~ /^$producer$/) AND $timeFilter GROUP BY time(5m), \"source\" fill(null)) WHERE $timeFilter GROUP BY time(5m)\n",
     "select": [
      [
       { "params": [ "numPeers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BGP peers pending",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Peer Pending",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sys/bgp/inst",
     "query": "SELECT sum(peerP) FROM (SELECT last(\"numPeersPending\") as peerP FROM \"sys/bgp/inst\" WHERE (\"source\" =~ /^$producer$/) AND $timeFilter GROUP BY time(5m), \"source\" fill(null)) WHERE $timeFilter GROUP BY time(5m)\n",
     "select": [
      [
       { "params": [ "numPeers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BGP peers pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sys/bgp/inst",
     "query": "SELECT last(\"numPeers\") - last(\"numEstPeers\") FROM \"sys/bgp/inst\" WHERE (\"source\" =~ /^$producer$/) AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "numPeers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "-" ], "type": "math" }
      ],
      [
       { "params": [ "numEstPeers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "producer", "operator": "=~", "value": "/^$producer$/" }
     ]
    }
   ]
  },
  {
   "title": "L2VPN received prefixes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "Prefix" }
   ],
   "targets": [
    {
     "alias": "Received prefixes",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "show bgp l2vpn evpn summary",
     "select": [
      [
       { "params": [ "prefixreceived" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$producer$/" }
     ]
    }
   ]
  },
  {
   "title": "L2VPN MSG received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "Msg" }
   ],
   "targets": [
    {
     "alias": "MSG received",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "show bgp l2vpn evpn summary",
     "select": [
      [
       { "params": [ "msgrecvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$producer$/" }
     ]
    }
   ]
  },
  {
   "title": "L2VPN MSG sent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "Msg" }
   ],
   "targets": [
    {
     "alias": "MSG sent",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "show bgp l2vpn evpn summary",
     "select": [
      [
       { "params": [ "msgsent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$producer$/" }
     ]
    }
   ]
  }
 ]
}